/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_diegosilva_rfnative_RfNative */

#ifndef _Included_br_com_diegosilva_rfnative_RfNative
#define _Included_br_com_diegosilva_rfnative_RfNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_diegosilva_rfnative_RfNative
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_com_diegosilva_rfnative_RfNative_start
  (JNIEnv *, jobject);

/*
 * Class:     br_com_diegosilva_rfnative_RfNative
 * Method:    send
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_diegosilva_rfnative_RfNative_send
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
