/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_diegosilva_rfnative_RfNative */

#ifndef _Included_br_com_diegosilva_rfnative_RfNative
#define _Included_br_com_diegosilva_rfnative_RfNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_diegosilva_rfnative_RfNative
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_diegosilva_rfnative_RfNative_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
