name: housepy
description: Client for home automation server.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: 0.16.1
  mobx: 1.2.1
  flutter_mobx: 1.1.0
  rxdart: 0.24.1
  shared_preferences: 0.5.7+3
  flutter_masked_text: 0.8.0
  bot_toast: 3.0.0
  modal_progress_hud: ^0.1.3
  google_fonts: ^1.1.0
  font_awesome_flutter: 8.8.1
  dio: 3.0.9
  web_socket_channel: 1.1.0
  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.0
  mobx_codegen: 1.1.0

flutter:
  assets:
    - fonts/google_fonts/
  uses-material-design: true