name: housepy
description: Client for home automation server.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.0.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  flutter_masked_text: 0.8.0
  bot_toast: ^4.0.1
  flutter_hud: ^0.3.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  dio: ">=4.0.0 <6.0.0"
  web_socket_channel: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.1+3

flutter:
  assets:
    - fonts/google_fonts/
  uses-material-design: true