name: housepy
description: Client for home automation server.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 1.1.1
  flutter_mobx: 1.1.0
  provider: 4.1.0-dev+3
  rxdart: 0.24.0
  shared_preferences: 0.5.7
  flutter_masked_text: 0.8.0
  bot_toast: ^2.4.1
  flutter_progress_hud: 1.0.2
  google_fonts: ^1.0.0
  font_awesome_flutter: 8.8.1
  web_socket_channel: 1.1.0
  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.9.0
  mobx_codegen: 1.0.3

flutter:
  assets:
    - fonts/google_fonts/
  uses-material-design: true